<?php
/**
 * User: Lh
 * Date: 2019/6/9 13:11
 */

namespace app\index\controller;


use think\Controller;

class Base extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function HotRes($cid)
    {
        //热门文章
        $art = new Artlist();
        $id = input('id');
        if(empty($id)){
            //热门文章有条件
            $hotres = $art->HotRes_y($cid);
        }else{
            $hotres = $art->HotRes();
        }
        cache('hotres',$hotres);
        $this->assign('hotres',cache('hotres'));
    }
    //导航栏目
    public function getNavCates()
    {
        $cate = new Cate();
        $cateres = $cate->where(['pid'=>0])->order('sort desc')->select();
        //找出子栏目
        foreach ($cateres as $k => $v) {
            $children = $cate->where(['pid'=>$v['id']])->order('sort desc')->select();
            if($children){
                $cateres[$k]['children']=$children;
            }else{
                $cateres[$k]['children']=0;
            }
        }
        $this->assign('cateres',$cateres);
        // dump($cateres);
    }
    //系统配置
    public function getConf()
    {
        $conf = new Conf();
        $conf_res = $conf->getAllConf();
        $conf_arr = array();
        foreach ($conf_res as $k => $v) {
            //  'comment' => string '允许评论' (length=12)
            $conf_arr[$v['en_name']]=$v['value'];
            // $conf_arr[$v['en_name']]=$v['cn_name'];
        }
        // dump($conf_arr);
        if($conf_arr['close'] == '是'){
            abort(404,'系统出错！');
        }
        $this->assign('confres',$conf_arr);
    }
    //轮播图
    public function slider()
    {
        $imgres = DB::name('img')->limit(4)->field('pic,url,desc')->where(['status'=>1])->select();
        $this->assign('imgres',$imgres);
    }
    //面包屑
    public function Xue($cid)
    {
        $cate = new Cate();
        $xue = $cate->getparents($cid);//面包屑
        $this->assign('xue',$xue);
    }
    //友情链接
    public function Link()
    {
        $link = Link::where('status',1)->order('sort ASC')->select();
        cache('link',$link);
        $this->assign('link',cache('link'));
    }
    //右侧广告图
    public function rec_right()
    {
        $rec_index = DB::name('img')->limit(1)->where(['status'=>1,'rec_index'=>2])->find();
        cache('arr',$rec_index);
        $this->assign('rec_right',cache('arr'));
    }

    // 解析urldeocde并截取
    public function cutstr_html($string, $sublen)
    {
        $string = strip_tags($string);
        $string = preg_replace ('/\n/is', '', $string);
        $string = preg_replace ('/ |　/is', '', $string);
        $string = preg_replace ('/&nbsp;/is', '', $string);

        preg_match_all("/[\x01-\x7f]|[\xc2-\xdf][\x80-\xbf]|\xe0[\xa0-\xbf][\x80-\xbf]|[\xe1-\xef][\x80-\xbf][\x80-\xbf]|\xf0[\x90-\xbf][\x80-\xbf][\x80-\xbf]|[\xf1-\xf7][\x80-\xbf][\x80-\xbf][\x80-\xbf]/", $string, $t_string);
        if(count($t_string[0]) - 0 > $sublen) $string = join('', array_slice($t_string[0], 0, $sublen))."…";
        else $string = join('', array_slice($t_string[0], 0, $sublen));

        return $string;
    }
}